<?php

//FRONT CONTROLLER


/*
    1) UMUMIY SOZLAMALAR / GENERAL SETTINGS

 * SAYTDAGI XATOLIKLARNI BATAFSIL KO'RSATADI / VIEW MORE DETAILS ERRORS ON THE SITE
 * PROYEKT ISHGA TUSHGANDA O'CHIRIB QO'YILADI / THE PROJECT WILL BE CLOSED WHEN IT IS STARTED
 */
ini_set('display_errors', 1);
error_reporting(E_ALL);
/* END */


/*
    2) SISTEMAGA FAYLLARNI ULASH / CONNECTING FILES TO THE SYSTEM

 * PROYEKTNI TO'LIQ JOYLASHUVINI ANIQLAB OLISH / DETERMINING THE FULL LOCATION OF THE PROJECT
 * VA ROUTERGA BOG'LANISH / AND CONNECTING TO A ROUTER
 */
define('ROOT', dirname(__FILE__));
require_once(ROOT.'/components/Router.php');


/*
    3) BAZA BILAN ALOQANI O'RNATISH / CONNECT TO DATABASE

 * 
 */



/*
    4) ROUTERNI ISHGA TUSHIRISH / RUN TO ROUTER

 * 
 */
$router = new Router();
$router->run();
